export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_RESPONSE = "USER_REGISTER_RESPONSE";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_START = "USER_LOGOUT_START";
export const USER_LOGOUT_RESPONSE = "USER_LOGOUT_RESPONSE";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";
